# Generated by Django 2.0.7 on 2020-12-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dress', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dress',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dress',
            name='variety',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
