# Generated by Django 2.1.7 on 2020-12-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dress', '0003_dress_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='dress',
            name='image',
            field=models.ImageField(default='default.png', upload_to='dress_pic'),
        ),
    ]
