# Generated by Django 2.1.7 on 2020-12-29 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dress', '0004_dress_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dress',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='dress_pic'),
        ),
    ]
